name: build_and_deploy

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.4.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x
      # - name: add config
      #   run: echo "${{ secrets.CONFIG_JSON }}" | base64 -d > src/config.json
      # - name: build
      #   run: npm install && npm run build
      - name: npm ci
        run: rm -rf node_modules && rm package-lock.json && npm install
      - name: validate dependencies
        run: ls -l node_modules/@tapis/tapisui-common
      - name: Build the project
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
